services:
  jekyll:
    build: .
    ports:
      - "4000:4000"
    volumes:
      # Mount the source code for development
      - .:/app
      # Exclude the _site directory to avoid conflicts
      - /app/_site
    environment:
      - JEKYLL_ENV=development
    command: bundle exec jekyll serve --host 0.0.0.0 --port 4000 --livereload 